server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/notification/**

        - id: user-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/user/**

        - id: product-catalog-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/product/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/